### ISSUE TITLE
Support for stdlib (>= 5.0.0)

### ISSUE THREAD

**Issue by markdv77** [pegasd/puppet-incron#6]
Hi,

Is it possible for puppet-incron to support a more recent version of stdlib?
The current limitation of <5.0.0 is holding me back from upgrading other modules to versions that require stdlib >=5.0.0.

Thanks,
Mark.

**Comment by pegasd** [comment]
Hi, @markdv77 !
Thanks for your interest in my project.

Sure thing, I'll release a new version with fixed stdlib version requirements!

**Comment by pegasd** [comment]
0.6.0 is out on the Forge. Enjoy!

**Comment by markdv77** [comment]
Thank you! Much appreciated.
